# Generated by Django 4.2.6 on 2023-10-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_apikey_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='rotation_order',
        ),
    ]
