# Generated by Django 4.2.7 on 2025-11-15 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0005_mealplan_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='User request that triggered generation')),
                ('title', models.CharField(max_length=255)),
                ('data', models.JSONField(help_text='Structured recipe content produced by AI')),
                ('diet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('excluded_ingredients', models.TextField(blank=True, help_text='Comma-separated excluded ingredients/allergens', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
