# Generated by Django 4.2.7 on 2025-11-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_contact'),
        ('Home', '0006_generatedrecipe'),
    ]

    operations = [
    ]
