# Generated by Django 4.2.7 on 2025-11-14 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('height_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('weight_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('target_weight_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('goal', models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintain', 'Maintain Current Weight'), ('improve_health', 'Improve Overall Health'), ('athlete', 'Athletic Performance'), ('manage_condition', 'Manage Health Condition')], max_length=50, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary (Little or no exercise)'), ('light', 'Light (Exercise 1-3 days/week)'), ('moderate', 'Moderate (Exercise 3-5 days/week)'), ('very_active', 'Very Active (Exercise 6-7 days/week)'), ('extreme', 'Extremely Active (Intense exercise daily)')], max_length=20, null=True)),
                ('daily_calorie_target', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(5000)])),
                ('diet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_cuisines', models.CharField(blank=True, max_length=500, null=True)),
                ('cooking_skill', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('average_cooking_time', models.IntegerField(blank=True, null=True)),
                ('kitchen_equipment', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('intolerances', models.TextField(blank=True, null=True)),
                ('favorite_ingredients', models.TextField(blank=True, null=True)),
                ('disliked_ingredients', models.TextField(blank=True, null=True)),
                ('budget_preference', models.CharField(choices=[('economical', 'Economical'), ('moderate', 'Moderate'), ('premium', 'Premium')], default='moderate', max_length=20)),
                ('diabetes', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('celiac', models.BooleanField(default=False)),
                ('lactose_intolerant', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('other_conditions', models.TextField(blank=True, null=True)),
                ('meals_per_day', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('prefer_meal_prep', models.BooleanField(default=False)),
                ('meal_prep_frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20, null=True)),
                ('min_recipe_rating', models.FloatField(default=3.5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('prefer_simple_recipes', models.BooleanField(default=True)),
                ('prefer_healthy', models.BooleanField(default=True)),
                ('spice_level', models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('spicy', 'Spicy'), ('very_spicy', 'Very Spicy')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferences_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
